import "./globals.css";
import NavbarPage from "@/components/shared/Navbar";
import FooterPage from "@/components/shared/Footer";
import { FriendProvider } from '@/context/FriendContext';
import { Geist } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
 
const geist = Geist({
  subsets: ['latin'],
})

export const metadata = {
  title: "KeenKeeper | Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={geist.className}
    >
      <body className="min-h-full">
        <FriendProvider>
          <NavbarPage />
          {children}
          <FooterPage />
          <ToastContainer position="top-right" />
        </FriendProvider>
      </body>
    </html>
  );
}
