import "./globals.css";
import NavbarPage from "@/components/shared/Navbar";
import FooterPage from "@/components/shared/Footer";
import { Geist } from 'next/font/google'
 
const geist = Geist({
  subsets: ['latin'],
})

export const metadata = {
  title: "KeenKeeper | Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={geist.className}
    >
      <body className="min-h-full">
        <NavbarPage></NavbarPage>
        {children}
        <FooterPage></FooterPage>
      </body>
    </html>
  );
}
